@rem This batch file builds and runs dsPIC30 filter code generated by dsPICFD.

@rem Environment variable requirements:
@rem   1. PATH contains pic30tools/bin
@rem   2. C_INCLUDE_PATH contains the pic30tools/include
@rem   3. LD_LIBRARY_PATH contains the pic30tools/lib

pic30-as -o IIRT_Filter.o IIRT_Filter.s
pic30-as -o IIR_Filter.o IIR_Filter.s
pic30-gcc -c -o IIR_Filter_sim.o IIR_Filter_sim.c
pic30-ld -defsym HEAPSIZE=4096 -L%LD_LIBRARY_PATH% IIR_Filter_sim.o IIR_Filter.o IIRT_Filter.o -lsxl -lpic30 -lsoftfloat -o IIR_Filter_sim.cof -Map IIR_Filter_sim.map
pic30-bin2hex IIR_Filter_sim.cof
simpic30 IIR_Filter_sim.cmd
